### ISSUE TITLE
ImportError: libIex-2_2.so.12

### ISSUE THREAD

**Issue by 686579206d616e** [tappi287/usdzconvert_webui#14]
Hello, can you help me with this error? (Debian 10)

First of all i tried to run serve.py, but got error:

```
03.09.2021 12:20 usdz_webui.modules.create_process INFO:   File "/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/usdzconvert/usdzconvert", line 17, in <module>
03.09.2021 12:20 usdz_webui.modules.create_process INFO:     usdUtils.printError("failed to import pxr module. Please add path to USD Python bindings to your PYTHONPATH.")
```

tried to add PYTHONPATH and PATH:

```
export PYTHONPATH="MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/lib/python:$PYTHONPATH"
export PATH="MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD:$PATH"
export PATH="MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/usdzconvert:$PATH"
export PYTHONPATH="MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/usdzconvert:$PYTHONPATH"
export PATH="MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/lib:$PATH"
export PATH="MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/bin:$PATH"
export PATH="MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/plugin/usd:$PATH"
```

But it does not helps.
Then i just tried to import pxr
```
cd usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804
python2 run_usd.py
```

Output:
```
(usdzconvert_webui) ➜  pxr_usd_abc1710_py27_ubuntu1804 python2 run_usd.py
['run_usd.py']
Extending PYTHONPATH with: MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/usdzconvert
Skipping non-existing path: USD/deps/usdview-deps-python
Extending PYTHONPATH with: MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/lib/python
Skipping non-existing path: USD/deps/python
Extending PATH with: MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/lib
Extending PATH with: MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/bin
Extending PATH with: MYPATH/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/plugin/usd
##########################################################################
No arguments provided, running python2.7 interpreter with USD environment.
##########################################################################
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Next `>>> from pxr import *`

Output:

```>>> from pxr import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/lib/python/pxr/UsdAbc/__init__.py", line 24, in <module>
    import _usdAbc
ImportError: libIex-2_2.so.12: cannot open shared object file: No such file or directory
```

Symlink exists into : `usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/lib`
`libIex-2_2.so.12` and file exists `libIex-2_2.so.12.0.0`, 

`echo $PATH`

Output:
```
MYPATH/share/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/plugin/usd:
MYPATH/share/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/bin:
MYPATH/share/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD/lib:
MYPATH/share/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/usdzconvert:
MYPATH/share/usdzconvert_webui/instance/converter/pxr_usd_abc1710_py27_ubuntu1804/USD:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

I have installed Pixar USD into:
```
/usr/local/USD/lib/python
/usr/local/USD/bin
```
`python3` then `>>> from pxr import *` - its works

Have any ideas? Or its will not works on Debian 10? Only for Ubuntu?

**Comment by 686579206d616e** [comment]
Yep, its works only on Ubuntu 18.04

**Comment by tappi287** [comment]
Thanks for the feeback.
